package models

type CIF struct {
	ID                                      string                   `json:"id"`
	NamaNasabah                             string                   `json:"namanasabah"`
	JenisNasabah                            string                   `json:"jenisnasabah"`
	PeroranganLamaMenempatiTahun            int64                    `json:"perorangan_lamamenempatitahun"`
	PeroranganLamaMenempatiBulan            int64                    `json:"perorangan_lamamenempatibulan"`
	PeroranganAlamatEmail                   string                   `json:"perorangan_alamatemail"`
	PerusahaanNoNpwp                        string                   `json:"perusahaan_nonpwp"`
	PerusahaanJenisBadanUsaha               string                   `json:"perusahaan_jenisbadanusaha"`
	PerusahaanNoAktaAwalBerdiri             string                   `json:"perusahaan_noaktaawalberdiri"`
	PerusahaanTempatAktaAwal                string                   `json:"perusahaan_tempataktaawal"`
	PerusahaanTglAktaAwal                   DateTZ                   `json:"perusahaan_tglaktaawal"`
	PerusahaanNoAktaAkhirBerdiri            string                   `json:"perusahaan_noaktaakhirberdiri"`
	PerusahaanTempatAktaAkhir               string                   `json:"perusahaan_tempataktaakhir"`
	PerusahaanTglAktaAkhir                  DateTZ                   `json:"perusahaan_tglaktaakhir"`
	DataPekerjaanLamaBekerjaTahun           int64                    `json:"datapekerjaan_lamabekerjatahun"`
	DataPekerjaanLamaBekerjaBulan           int64                    `json:"datapekerjaan_lamabekerjabulan"`
	DataPekerjaanLamaBekerjaSebelumnyaTahun int64                    `json:"datapekerjaan_lamabekerjasebelumnyatahun"`
	DataPekerjaanLamaBekerjaSebelumnyaBulan int64                    `json:"datapekerjaan_lamabekerjasebelumnyabulan"`
	DataAlamatKtpAlamat1                    string                   `json:"dataalamat_ktp_alamat1"`
	DataAlamatKtpKelurahan                  string                   `json:"dataalamat_ktp_kelurahan"`
	DataAlamatKtpKecamatan                  string                   `json:"dataalamat_ktp_kecamatan"`
	DataAlamatKtpKota                       string                   `json:"dataalamat_ktp_kota"`
	DataAlamatKtpKodePos                    string                   `json:"dataalamat_ktp_kodepos"`
	DataAlamatKtpPropinsi                   string                   `json:"dataalamat_ktp_propinsi"`
	DataAlamatAlamatKantorAdalahAlamatAkta  string                   `json:"dataalamat_alamatkantoradalahalamatakta"`
	DataAlamatKantorAlamat1                 string                   `json:"dataalamat_kantor_alamat1"`
	DataAlamatKantorKelurahan               string                   `json:"dataalamat_kantor_kelurahan"`
	DataAlamatKantorKecamatan               string                   `json:"dataalamat_kantor_kecamatan"`
	DataAlamatKantorKota                    string                   `json:"dataalamat_kantor_kota"`
	DataAlamatKantorKodePos                 int64                    `json:"dataalamat_kantor_kodepos"`
	DataAlamatKantorPropinsi                string                   `json:"dataalamat_kantor_propinsi"`
	DataAlamatKantorNoHp                    string                   `json:"dataalamat_kantor_nohp"`
	DataKontakLainnyaKodePos                int64                    `json:"datakontaklainnya_kodepos"`
	DataPenjaminKodePos                     int64                    `json:"datapenjamin_kodepos"`
	DataPenjaminLamaBekerjaTahun            int64                    `json:"datapenjamin_lamabekerjatahun"`
	DataPenjaminLamaBekerjaBulan            int64                    `json:"datapenjamin_lamabekerjabulan"`
	DataUntukSidNamaAlias                   string                   `json:"datauntuksid_namaalias"`
	DataKycLimitTransaksiSetoranTunai       int64                    `json:"datakyc_limittransaksi_setorantunai"`
	DataKycLimitTransaksiSetoranNonTunai    int64                    `json:"datakyc_limittransaksi_setorannontunai"`
	DataKycLimitTransaksiPenarikanTunai     int64                    `json:"datakyc_limittransaksi_penarikantunai"`
	DataKycLimitTransaksiPenarikanNonTunai  int64                    `json:"datakyc_limittransaksi_penarikannontunai"`
	DataKycLimitTransaksiFrekuensi          int64                    `json:"datakyc_limittransaksi_frekuensi"`
	DataKycDataNasabahPerusahaanPenghasilan int64                    `json:"datakyc_datanasabahperusahaan_penghasilan"`
	TglBukaCif                              DateTZ                   `json:"tglbukacif"`
	KolekBiManual                           int64                    `json:"kolekbi_manual"`
	KolekBprManual                          int64                    `json:"kolekbpr_manual"`
	KolekBIPinjaman                         int64                    `json:"kolekbi_pinjaman"`
	KolekBPRPinjaman                        int64                    `json:"kolekbpr_pinjaman"`
	RecKoreksiOleh                          string                   `json:"rec_koreksi_oleh"`
	RecKoreksiTglJam                        Rec                      `json:"rec_koreksi_tgljam"`
	RecKoreksiLokasi                        string                   `json:"rec_koreksi_lokasi"`
	ProfilRisikoIdentitasNasabah            string                   `json:"profilresiko_identitasnasabah"`
	ProfilRisikoLokasiUsaha                 string                   `json:"profilresiko_lokasiusaha"`
	ProfilRisikoJumlahTransaksi             string                   `json:"profilresiko_jumlahtransaksi"`
	ProfilRisikoKegiatanUsaha               string                   `json:"profilresiko_kegiatanusaha"`
	ProfilRisikoStrukturKepemilikan         string                   `json:"profilresiko_strukturkepemilikan"`
	ProfilRisikoProdukJasaJaringan          string                   `json:"profilresiko_produkjasajaringan"`
	ProfilRisikoInformasiLain               string                   `json:"profilresiko_informasilain"`
	ProfilRisikoResumeAkhir                 string                   `json:"profilresiko_resumeakhir"`
	ProfilRisikoProfil                      string                   `json:"profilresiko_profil"`
	RecDibuatOleh                           string                   `json:"rec_dibuat_oleh"`
	RecDibuatTglJam                         Rec                      `json:"rec_dibuat_tgljam"`
	RecDibuatLokasi                         string                   `json:"rec_dibuat_lokasi"`
	RecDiupdateOleh                         string                   `json:"rec_diupdate_oleh"`
	RecDiupdateTglJam                       Rec                      `json:"rec_diupdate_tgljam"`
	RecDiupdateLokasi                       string                   `json:"rec_diupdate_lokasi"`
	RecTimestamp                            Rec                      `json:"rec_timestamp"`
	DataPengurusPerusahaan                  []DataPengurusPerusahaan `json:"datapengurusperusahaan"`
	CustomField                             []any                    `json:"customfield"`
	DataDiklat                              []any                    `json:"datadiklat"`
	DataAhliWaris                           []DataAhliWaris          `json:"dataahliwaris"`
	StatusDokumen                           string                   `json:"status_dokumen"`
	PlafondLimit                            any                      `json:"plafondlimit"`
	Tabungan                                []struct {
		ID              string `json:"id"`
		Currency        string `json:"currency"`
		StatusDokumen   string `json:"status_dokumen"`
		NoAlt           any    `json:"noalt"`
		TglBukaRekening string `json:"tglbukarekening"`
		Nama            string `json:"nama"`
	} `json:"tabungan"`
	Location struct {
		LocationName string `json:"locationname"`
	} `json:"location"`
}

type DataPengurusPerusahaan struct {
	ID                      string  `json:"id"`
	NoCif                   string  `json:"nocif"`
	NoUrut                  int64   `json:"nourut"`
	Nama                    string  `json:"nama"`
	NoNpwp                  string  `json:"nonpwp"`
	TempatLahir             string  `json:"tempatlahir"`
	TglLahir                DateTZ  `json:"tgllahir"`
	JenisKelamin            string  `json:"jeniskelamin"`
	NoKtp                   string  `json:"noktp"`
	TglDikeluarkan          any     `json:"tgldikeluarkan"`
	BerlakuSampai           any     `json:"berlakusampai"`
	BerlakuSeumurHidup      any     `json:"berlakuseumurhidup"`
	JabatanPengurus         string  `json:"jabatanpengurus"`
	KepemilikanSaham        int64   `json:"kepemilikansaham"`
	AlamatPengurusAlamat1   string  `json:"alamatpengurus_alamat1"`
	AlamatPengurusAlamat2   string  `json:"alamatpengurus_alamat2"`
	AlamatPengurusRt        string  `json:"alamatpengurus_rt"`
	AlamatPengurusRw        string  `json:"alamatpengurus_rw"`
	AlamatPengurusKelurahan string  `json:"alamatpengurus_kelurahan"`
	AlamatPengurusKecamatan string  `json:"alamatpengurus_kecamatan"`
	AlamatPengurusKota      string  `json:"alamatpengurus_kota"`
	AlamatPengurusPropinsi  string  `json:"alamatpengurus_propinsi"`
	AlamatPengurusKodePos   string  `json:"alamatpengurus_kodepos"`
	AlamatPengurusKodeArea  string  `json:"alamatpengurus_kodearea"`
	AlamatPengurusNoTelp    string  `json:"alamatpengurus_notelp"`
	AlamatPengurusNoHp      string  `json:"alamatpengurus_nohp"`
	AlamatPengurusNoFax     string  `json:"alamatpengurus_nofax"`
	TempatDikeluarkan       *string `json:"tempat_dikeluarkan"`
	RecTimestamp            Rec     `json:"rec_timestamp"`
}

type DataAhliWaris struct {
	ID                    string `json:"id"`
	NoUrut                string `json:"nourut"`
	NoCif                 string `json:"nocif"`
	AhliWarisNama         any    `json:"ahliwaris_nama"`
	AhliWarisHubDgnKontak any    `json:"ahliwaris_hubdgnkontak"`
	AhliWarisAlamat1      any    `json:"ahliwaris_alamat1"`
	AhliWarisAlamat2      any    `json:"ahliwaris_alamat2"`
	AhliWarisRt           any    `json:"ahliwaris_rt"`
	AhliWarisRw           any    `json:"ahliwaris_rw"`
	AhliWarisKelurahan    any    `json:"ahliwaris_kelurahan"`
	AhliWarisKecamatan    any    `json:"ahliwaris_kecamatan"`
	AhliWarisKota         any    `json:"ahliwaris_kota"`
	AhliWarisPropinsi     any    `json:"ahliwaris_propinsi"`
	AhliWarisNoTelp       any    `json:"ahliwaris_notelp"`
	AhliWarisNoHp         any    `json:"ahliwaris_nohp"`
	AhliWarisNoFax        any    `json:"ahliwaris_nofax"`
	AhliWarisKodePos      string `json:"ahliwaris_kodepos"`
	RecTimestamp          Rec    `json:"rec_timestamp"`
}
