package models

type Saving struct {
	LocationID                     string              `json:"locationid"`
	RecDibuatLokasi                string              `json:"rec_dibuat_lokasi"`
	NoAlt                          string              `json:"noalt"`
	NoAlt2                         any                 `json:"noalt2"`
	NoCif                          string              `json:"nocif"`
	ProdukID                       string              `json:"produkid"`
	NoRekening                     string              `json:"norekening"`
	Nama                           string              `json:"nama"`
	StatusDokumen                  string              `json:"status_dokumen"`
	StatusCif                      string              `json:"status_cif"`
	CreateDate                     DateTZ              `json:"createdate"`
	CreatedBy                      string              `json:"createdby"`
	ProdukJenisTabungan            string              `json:"produk_jenistabungan"`
	Currency                       string              `json:"currency"`
	SukuBungaKredit                string              `json:"sukubungakredit"`
	PembayaranBungaKreditTglTetap  float64             `json:"pembayaranbunga_kredit_tgltetap"`
	SukuBungaDebit                 any                 `json:"sukubungadebit"`
	PembayaranBungaDebitTglTetap   float64             `json:"pembayaranbunga_debit_tgltetap"`
	Overdraft                      string              `json:"overdraft"`
	NoRekTujuanBunga               any                 `json:"norek_tujuan_bunga"`
	NamaNasabah                    string              `json:"namanasabah"`
	JenisTabungan                  string              `json:"jenistabungan"`
	CetakBilyet                    string              `json:"cetakbilyet"`
	CetakBukuTabungan              string              `json:"cetakbukutabungan"`
	ProdukSukuBungaDebit           float64             `json:"produk_sukubungadebit"`
	ProdukSukuBungaKredit          float64             `json:"produk_sukubungakredit"`
	Referral                       any                 `json:"referral"`
	ProdukTransaksiAutoDebit       string              `json:"produk_transaksiautodebit"`
	TujuanPembukaanRekening        string              `json:"tujuanpembukaanrekening"`
	SumberDana                     any                 `json:"sumberdana"`
	JointAccount                   string              `json:"jointaccount"`
	AlasanBlokir                   any                 `json:"alasanblokir"`
	NilaiBukaBlokir                float64             `json:"nilaibukablokir"`
	TglBlokir                      any                 `json:"tglblokir"`
	TglAkhirBlokir                 any                 `json:"tglakhirblokir"`
	KeteranganBlokir               any                 `json:"keteranganblokir"`
	TglBukaBlokir                  any                 `json:"tglbukablokir"`
	AlasanBukaBlokir               any                 `json:"alasanbukablokir"`
	SaldoBlokir                    float64             `json:"saldoblokir"`
	TglBukaRekening                DateTZ              `json:"tglbukarekening"`
	TglClosed                      any                 `json:"tglclosed"`
	BlokirDebet                    any                 `json:"blokirdebet"`
	BlokirKredit                   any                 `json:"blokirkredit"`
	NamaRek                        string              `json:"namarek"`
	NamaLain                       any                 `json:"namalain"`
	JenisNasabah                   string              `json:"jenisnasabah"`
	DataAlamatKtpAlamat1           string              `json:"dataalamat_ktp_alamat1"`
	TglBukaCif                     DateTZ              `json:"tglbukacif"`
	DataAlamatKtpAlamat2           any                 `json:"dataalamat_ktp_alamat2"`
	DataAlamatKtpRt                string              `json:"dataalamat_ktp_rt"`
	DataAlamatKtpRw                string              `json:"dataalamat_ktp_rw"`
	DataAlamatKtpPropinsi          string              `json:"dataalamat_ktp_propinsi"`
	DataAlamatKtpKota              string              `json:"dataalamat_ktp_kota"`
	DataAlamatKtpKecamatan         string              `json:"dataalamat_ktp_kecamatan"`
	DataAlamatKtpKelurahan         string              `json:"dataalamat_ktp_kelurahan"`
	DataAlamatKtpKodepos           string              `json:"dataalamat_ktp_kodepos"`
	SaldoAwal                      float64             `json:"saldoawal"`
	SaldoAkhir                     float64             `json:"saldoakhir"`
	MutasiDebit                    string              `json:"mutasidebit"`
	MutasiKredit                   string              `json:"mutasikredit"`
	SaldoAkru                      float64             `json:"saldoakru"`
	SaldoAkruDebit                 float64             `json:"saldoakrudebit"`
	PlafondLimit                   float64             `json:"plafondlimit"`
	Dpd                            int64               `json:"dpd"`
	KolekBi                        int64               `json:"kolekbi"`
	Tunggakan                      any                 `json:"tunggakan"`
	DendaTunggakan                 any                 `json:"denda_tunggakan"`
	TglMulaiTunggakan              any                 `json:"tgl_mulai_tunggakan"`
	TglBayarTerakhir               any                 `json:"tgl_bayar_terakhir"`
	SidGolonganKredit              any                 `json:"sid_golongankredit"`
	SidJenisPenggunaan             any                 `json:"sid_jenispenggunaan"`
	SidJenisUsaha                  any                 `json:"sid_jenisusaha"`
	SidOrientasiPenggunaan         any                 `json:"sid_orientasipenggunaan"`
	SidSumberDanaPelunasan         any                 `json:"sid_sumberdanapelunasan"`
	SidSifatKredit                 any                 `json:"sid_sifatkredit"`
	SidSifatKredit2                any                 `json:"sid_sifatkredit2"`
	SidSektorEkonomi               any                 `json:"sid_sektorekonomi"`
	SidSektorEkonomi2              any                 `json:"sid_sektorekonomi2"`
	Terpakai                       float64             `json:"terpakai"`
	PlafondBlokir                  string              `json:"plafond_blokir"`
	TotalSoAktif                   float64             `json:"total_so_aktif"`
	TotalUsedPlafondOd1            float64             `json:"totalusedplafondod1"`
	TotalAvailablePlafondOd1       float64             `json:"totalavailableplafondod1"`
	TotalAvailablePlafond          float64             `json:"totalavailableplafond"`
	LimitFasilitas                 float64             `json:"limitfasilitas"`
	PeriodeAwalFasilitas           any                 `json:"periodeawal_fasilitas"`
	PeriodeAkhirFasilitas          any                 `json:"periodeakhir_fasilitas"`
	PeriodeBatasFasilitasPencairan any                 `json:"periode_batas_fasilitas_pencairan"`
	KeteranganFasilitas            any                 `json:"keterangan_fasilitas"`
	ProdukBnpl                     string              `json:"produk_bnpl"`
	MidRate                        int64               `json:"mid_rate"`
	ServiceID                      any                 `json:"serviceid"`
	GroupID                        any                 `json:"groupid"`
	KodeMarketing                  any                 `json:"kode_marketing"`
	NotesMarketing                 any                 `json:"notes_marketing"`
	TotalAvailablePlafondOd        float64             `json:"totalavailableplafondod"`
	TotalUsedPlafondOd             float64             `json:"totalusedplafondod"`
	SaldoAwalKredit                string              `json:"saldoawalkredit"`
	SaldoAwalDebit                 string              `json:"saldoawaldebit"`
	SaldoAkhirKredit               string              `json:"saldoakhirkredit"`
	SaldoAkhirKreditEquivalent     string              `json:"saldoakhirkredit_equivalent"`
	SaldoAkhirDebit                string              `json:"saldoakhirdebit"`
	SaldoAkhirDebitEquivalent      string              `json:"saldoakhirdebit_equivalent"`
	SaldoAkruBungaKredit           float64             `json:"saldoakrubungakredit"`
	SaldoAkruBungaDebit            float64             `json:"saldoakrubungadebit"`
	DataStandingOrder              []DataStandingOrder `json:"datastandingorder"`
	AttKtp                         any                 `json:"attKtp"`
	AttTtd                         any                 `json:"attTtd"`
	StatusBlokir                   string              `json:"statusblokir"`
}

type DataStandingOrder struct {
	TglTransaksi  string `json:"tgltransaksi"`
	NoRekTujuan   string `json:"norektujuan"`
	NamaNasabah   string `json:"namanasabah"`
	Nominal       string `json:"nominal"`
	Frekuensi     string `json:"frekuensi"`
	XFrekuensi    int64  `json:"xfrekuensi"`
	TglAwal       string `json:"tglawal"`
	TglAkhir      string `json:"tglakhir"`
	TglBerikutnya string `json:"tglberikutnya"`
	Status        string `json:"status"`
	Keterangan    string `json:"keterangan"`
	Fee           string `json:"fee"`
}
