package models

type DateTZ struct {
	Date         string `json:"date" db:"date"`
	TimezoneType int64  `json:"timezone_type" db:"timezone_type"`
	Timezone     string `json:"timezone" db:"timezone"`
}

type Rec struct {
	Date string `json:"date" db:"date"`
	Type string `json:"type" db:"type"`
}

// type CIFPerorangan struct {
// 	ID                                      string                   `json:"id"`
// 	Namanasabah                             string                   `json:"namanasabah"`
// 	Jenisnasabah                            string                   `json:"jenisnasabah"`
// 	Jenisidentitas                          string                   `json:"jenisidentitas"`
// 	PeroranganNoktp                         string                   `json:"perorangan_noktp"`
// 	PeroranganTempatlahir                   string                   `json:"perorangan_tempatlahir"`
// 	PeroranganTgllahir                      DateTZ                   `json:"perorangan_tgllahir"`
// 	PeroranganJeniskelamin                  string                   `json:"perorangan_jeniskelamin"`
// 	PeroranganAgama                         string                   `json:"perorangan_agama"`
// 	PeroranganStatusperkawinan              string                   `json:"perorangan_statusperkawinan"`
// 	PeroranganPendidikanformal              string                   `json:"perorangan_pendidikanformal"`
// 	PeroranganNamaibukandung                string                   `json:"perorangan_namaibukandung"`
// 	PeroranganLamamenempatitahun            int64                    `json:"perorangan_lamamenempatitahun"`
// 	PeroranganLamamenempatibulan            int64                    `json:"perorangan_lamamenempatibulan"`
// 	PeroranganJenisanggota                  string                   `json:"perorangan_jenisanggota"`
// 	DatapekerjaanJenispekerjaan             string                   `json:"datapekerjaan_jenispekerjaan"`
// 	DatapekerjaanLamabekerjatahun           int64                    `json:"datapekerjaan_lamabekerjatahun"`
// 	DatapekerjaanLamabekerjabulan           int64                    `json:"datapekerjaan_lamabekerjabulan"`
// 	DatapekerjaanLamabekerjasebelumnyatahun int64                    `json:"datapekerjaan_lamabekerjasebelumnyatahun"`
// 	DatapekerjaanLamabekerjasebelumnyabulan int64                    `json:"datapekerjaan_lamabekerjasebelumnyabulan"`
// 	DataalamatKtpAlamat1                    string                   `json:"dataalamat_ktp_alamat1"`
// 	DataalamatKtpRt                         string                   `json:"dataalamat_ktp_rt"`
// 	DataalamatKtpRw                         string                   `json:"dataalamat_ktp_rw"`
// 	DataalamatKtpKelurahan                  string                   `json:"dataalamat_ktp_kelurahan"`
// 	DataalamatKtpKecamatan                  string                   `json:"dataalamat_ktp_kecamatan"`
// 	DataalamatKtpKota                       string                   `json:"dataalamat_ktp_kota"`
// 	DataalamatKtpKodepos                    string                   `json:"dataalamat_ktp_kodepos"`
// 	DataalamatKtpPropinsi                   string                   `json:"dataalamat_ktp_propinsi"`
// 	DataalamatAlamatrumahadalahalamatktp    string                   `json:"dataalamat_alamatrumahadalahalamatktp"`
// 	DataalamatRumahAlamat1                  string                   `json:"dataalamat_rumah_alamat1"`
// 	DataalamatRumahRt                       string                   `json:"dataalamat_rumah_rt"`
// 	DataalamatRumahRw                       string                   `json:"dataalamat_rumah_rw"`
// 	DataalamatRumahKelurahan                string                   `json:"dataalamat_rumah_kelurahan"`
// 	DataalamatRumahKecamatan                string                   `json:"dataalamat_rumah_kecamatan"`
// 	DataalamatRumahKota                     string                   `json:"dataalamat_rumah_kota"`
// 	DataalamatRumahKodepos                  string                   `json:"dataalamat_rumah_kodepos"`
// 	DataalamatRumahPropinsi                 string                   `json:"dataalamat_rumah_propinsi"`
// 	DataalamatRumahNohp                     string                   `json:"dataalamat_rumah_nohp"`
// 	DataalamatKantorKodepos                 int64                    `json:"dataalamat_kantor_kodepos"`
// 	DatakontaklainnyaKodepos                int64                    `json:"datakontaklainnya_kodepos"`
// 	DatapenjaminKodepos                     int64                    `json:"datapenjamin_kodepos"`
// 	DatapenjaminLamabekerjatahun            int64                    `json:"datapenjamin_lamabekerjatahun"`
// 	DatapenjaminLamabekerjabulan            int64                    `json:"datapenjamin_lamabekerjabulan"`
// 	DatauntuksidNamaalias                   string                   `json:"datauntuksid_namaalias"`
// 	DatauntuksidGolongandebitur             string                   `json:"datauntuksid_golongandebitur"`
// 	DatauntuksidDati2Debitur                string                   `json:"datauntuksid_dati2debitur"`
// 	DatakycLimittransaksiSetorantunai       int64                    `json:"datakyc_limittransaksi_setorantunai"`
// 	DatakycLimittransaksiSetorannontunai    int64                    `json:"datakyc_limittransaksi_setorannontunai"`
// 	DatakycLimittransaksiPenarikantunai     int64                    `json:"datakyc_limittransaksi_penarikantunai"`
// 	DatakycLimittransaksiPenarikannontunai  int64                    `json:"datakyc_limittransaksi_penarikannontunai"`
// 	DatakycLimittransaksiFrekuensi          int64                    `json:"datakyc_limittransaksi_frekuensi"`
// 	DatakycDatanasabahperusahaanPenghasilan int64                    `json:"datakyc_datanasabahperusahaan_penghasilan"`
// 	Noalt                                   string                   `json:"noalt"`
// 	Tglbukacif                              DateTZ                   `json:"tglbukacif"`
// 	KolekbiManual                           int64                    `json:"kolekbi_manual"`
// 	KolekbprManual                          int64                    `json:"kolekbpr_manual"`
// 	KolekbiPinjaman                         int64                    `json:"kolekbi_pinjaman"`
// 	KolekbprPinjaman                        int64                    `json:"kolekbpr_pinjaman"`
// 	DataktpNik                              string                   `json:"dataktp_nik"`
// 	DataktpNama                             string                   `json:"dataktp_nama"`
// 	DataktpTempatlahir                      string                   `json:"dataktp_tempatlahir"`
// 	DataktpJeniskelamin                     string                   `json:"dataktp_jeniskelamin"`
// 	DataktpAlamat                           string                   `json:"dataktp_alamat"`
// 	DataktpAgama                            string                   `json:"dataktp_agama"`
// 	DataktpStatusperkawinan                 string                   `json:"dataktp_statusperkawinan"`
// 	DataktpPekerjaan                        string                   `json:"dataktp_pekerjaan"`
// 	DataktpTgllahir                         DateTZ                   `json:"dataktp_tgllahir"`
// 	DatauntuksidStatus                      string                   `json:"datauntuksid_status"`
// 	DatalabulGolongandebitur                string                   `json:"datalabul_golongandebitur"`
// 	ProfilresikoIdentitasnasabah            string                   `json:"profilresiko_identitasnasabah"`
// 	ProfilresikoLokasiusaha                 string                   `json:"profilresiko_lokasiusaha"`
// 	ProfilresikoJumlahtransaksi             string                   `json:"profilresiko_jumlahtransaksi"`
// 	ProfilresikoKegiatanusaha               string                   `json:"profilresiko_kegiatanusaha"`
// 	ProfilresikoStrukturkepemilikan         string                   `json:"profilresiko_strukturkepemilikan"`
// 	ProfilresikoProdukjasajaringan          string                   `json:"profilresiko_produkjasajaringan"`
// 	ProfilresikoInformasilain               string                   `json:"profilresiko_informasilain"`
// 	ProfilresikoResumeakhir                 string                   `json:"profilresiko_resumeakhir"`
// 	ProfilresikoProfil                      string                   `json:"profilresiko_profil"`
// 	RecDibuatOleh                           string                   `json:"rec_dibuat_oleh"`
// 	RecDibuatTgljam                         Rec                      `json:"rec_dibuat_tgljam"`
// 	RecDibuatLokasi                         string                   `json:"rec_dibuat_lokasi"`
// 	RecDiupdateOleh                         string                   `json:"rec_diupdate_oleh"`
// 	RecDiupdateTgljam                       Rec                      `json:"rec_diupdate_tgljam"`
// 	RecDiupdateLokasi                       string                   `json:"rec_diupdate_lokasi"`
// 	RecTimestamp                            Rec                      `json:"rec_timestamp"`
// 	Datapengurusperusahaan                  []DataPengurusPerusahaan `json:"datapengurusperusahaan"`
// 	Customfield                             []any                    `json:"customfield"`
// 	Datadiklat                              []any                    `json:"datadiklat"`
// 	Dataahliwaris                           []DataAhliWaris          `json:"dataahliwaris"`
// 	StatusDokumen                           string                   `json:"status_dokumen"`
// 	Plafondlimit                            bool                     `json:"plafondlimit"`
// 	Location                                struct {
// 		LocationName string `json:"locationname"`
// 	} `json:"location"`
// }

// type CIFBadan struct {
// 	ID                                      string                   `json:"id"`
// 	Namanasabah                             string                   `json:"namanasabah"`
// 	Jenisnasabah                            string                   `json:"jenisnasabah"`
// 	Jenisidentitas                          string                   `json:"jenisidentitas"`
// 	PeroranganLamamenempatitahun            int64                    `json:"perorangan_lamamenempatitahun"`
// 	PeroranganLamamenempatibulan            int64                    `json:"perorangan_lamamenempatibulan"`
// 	PerusahaanNonpwp                        string                   `json:"perusahaan_nonpwp"`
// 	PerusahaanJenisbadanusaha               string                   `json:"perusahaan_jenisbadanusaha"`
// 	PerusahaanNoaktaawalberdiri             string                   `json:"perusahaan_noaktaawalberdiri"`
// 	PerusahaanTempataktaawal                string                   `json:"perusahaan_tempataktaawal"`
// 	PerusahaanTglaktaawal                   DateTZ                   `json:"perusahaan_tglaktaawal"`
// 	PerusahaanNoaktaakhirberdiri            string                   `json:"perusahaan_noaktaakhirberdiri"`
// 	PerusahaanTempataktaakhir               string                   `json:"perusahaan_tempataktaakhir"`
// 	PerusahaanTglaktaakhir                  DateTZ                   `json:"perusahaan_tglaktaakhir"`
// 	DatapekerjaanLamabekerjatahun           int64                    `json:"datapekerjaan_lamabekerjatahun"`
// 	DatapekerjaanLamabekerjabulan           int64                    `json:"datapekerjaan_lamabekerjabulan"`
// 	DatapekerjaanLamabekerjasebelumnyatahun int64                    `json:"datapekerjaan_lamabekerjasebelumnyatahun"`
// 	DatapekerjaanLamabekerjasebelumnyabulan int64                    `json:"datapekerjaan_lamabekerjasebelumnyabulan"`
// 	DataalamatKantorKodepos                 int64                    `json:"dataalamat_kantor_kodepos"`
// 	DatakontaklainnyaKodepos                int64                    `json:"datakontaklainnya_kodepos"`
// 	DatapenjaminKodepos                     int64                    `json:"datapenjamin_kodepos"`
// 	DatapenjaminLamabekerjatahun            int64                    `json:"datapenjamin_lamabekerjatahun"`
// 	DatapenjaminLamabekerjabulan            int64                    `json:"datapenjamin_lamabekerjabulan"`
// 	DatakycLimittransaksiSetorantunai       int64                    `json:"datakyc_limittransaksi_setorantunai"`
// 	DatakycLimittransaksiSetorannontunai    int64                    `json:"datakyc_limittransaksi_setorannontunai"`
// 	DatakycLimittransaksiPenarikantunai     int64                    `json:"datakyc_limittransaksi_penarikantunai"`
// 	DatakycLimittransaksiPenarikannontunai  int64                    `json:"datakyc_limittransaksi_penarikannontunai"`
// 	DatakycLimittransaksiFrekuensi          int64                    `json:"datakyc_limittransaksi_frekuensi"`
// 	DatakycDatanasabahperusahaanPenghasilan int64                    `json:"datakyc_datanasabahperusahaan_penghasilan"`
// 	Noalt                                   string                   `json:"noalt"`
// 	Tglbukacif                              DateTZ                   `json:"tglbukacif"`
// 	KolekbiManual                           int64                    `json:"kolekbi_manual"`
// 	KolekbprManual                          int64                    `json:"kolekbpr_manual"`
// 	KolekbiPinjaman                         int64                    `json:"kolekbi_pinjaman"`
// 	KolekbprPinjaman                        int64                    `json:"kolekbpr_pinjaman"`
// 	ProfilresikoIdentitasnasabah            string                   `json:"profilresiko_identitasnasabah"`
// 	ProfilresikoLokasiusaha                 string                   `json:"profilresiko_lokasiusaha"`
// 	ProfilresikoJumlahtransaksi             string                   `json:"profilresiko_jumlahtransaksi"`
// 	ProfilresikoKegiatanusaha               string                   `json:"profilresiko_kegiatanusaha"`
// 	ProfilresikoStrukturkepemilikan         string                   `json:"profilresiko_strukturkepemilikan"`
// 	ProfilresikoProdukjasajaringan          string                   `json:"profilresiko_produkjasajaringan"`
// 	ProfilresikoInformasilain               string                   `json:"profilresiko_informasilain"`
// 	ProfilresikoResumeakhir                 string                   `json:"profilresiko_resumeakhir"`
// 	ProfilresikoProfil                      string                   `json:"profilresiko_profil"`
// 	RecDibuatOleh                           string                   `json:"rec_dibuat_oleh"`
// 	RecDibuatTgljam                         Rec                      `json:"rec_dibuat_tgljam"`
// 	RecDibuatLokasi                         string                   `json:"rec_dibuat_lokasi"`
// 	RecDiupdateOleh                         string                   `json:"rec_diupdate_oleh"`
// 	RecDiupdateTgljam                       Rec                      `json:"rec_diupdate_tgljam"`
// 	RecDiupdateLokasi                       string                   `json:"rec_diupdate_lokasi"`
// 	RecTimestamp                            Rec                      `json:"rec_timestamp"`
// 	Datapengurusperusahaan                  []DataPengurusPerusahaan `json:"datapengurusperusahaan"`
// 	Customfield                             []any                    `json:"customfield"`
// 	Datadiklat                              []any                    `json:"datadiklat"`
// 	Dataahliwaris                           []DataAhliWaris          `json:"dataahliwaris"`
// 	StatusDokumen                           string                   `json:"status_dokumen"`
// 	Plafondlimit                            any                      `json:"plafondlimit"`
// 	Location                                struct {
// 		LocationName string `json:"locationname"`
// 	} `json:"location"`
// }
