CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(255) PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cifs (
    id VARCHAR(64) PRIMARY KEY,
    nama_nasabah TEXT,
    jenis_nasabah TEXT,
    perorangan_lamamenempatitahun BIGINT,
    perorangan_lamamenempatibulan BIGINT,
    perorangan_alamatemail TEXT,
    perusahaan_nonpwp TEXT,
    perusahaan_jenisbadanusaha TEXT,
    perusahaan_noaktaawalberdiri TEXT,
    perusahaan_tempataktaawal TEXT,
    perusahaan_tglaktaawal_date VARCHAR(64),
    perusahaan_tglaktaawal_timezone_type BIGINT,
    perusahaan_tglaktaawal_timezone VARCHAR(64),
    perusahaan_noaktaakhirberdiri TEXT,
    perusahaan_tempataktaakhir TEXT,
    perusahaan_tglaktaakhir_date VARCHAR(64),
    perusahaan_tglaktaakhir_timezone_type BIGINT,
    perusahaan_tglaktaakhir_timezone VARCHAR(64),
    datapekerjaan_lamabekerjatahun BIGINT,
    datapekerjaan_lamabekerjabulan BIGINT,
    datapekerjaan_lamabekerjasebelumnyatahun BIGINT,
    datapekerjaan_lamabekerjasebelumnyabulan BIGINT,
    dataalamat_ktp_alamat1 TEXT,
    dataalamat_ktp_kelurahan TEXT,
    dataalamat_ktp_kecamatan TEXT,
    dataalamat_ktp_kota TEXT,
    dataalamat_ktp_kodepos TEXT,
    dataalamat_ktp_propinsi TEXT,
    dataalamat_alamatkantoradalahalamatakta TEXT,
    dataalamat_kantor_alamat1 TEXT,
    dataalamat_kantor_kelurahan TEXT,
    dataalamat_kantor_kecamatan TEXT,
    dataalamat_kantor_kota TEXT,
    dataalamat_kantor_kodepos BIGINT,
    dataalamat_kantor_propinsi TEXT,
    dataalamat_kantor_nohp TEXT,
    datakontaklainnya_kodepos BIGINT,
    datapenjamin_kodepos BIGINT,
    datapenjamin_lamabekerjatahun BIGINT,
    datapenjamin_lamabekerjabulan BIGINT,
    datauntuksid_namaalias TEXT,
    datakyc_limittransaksi_setorantunai BIGINT,
    datakyc_limittransaksi_setorannontunai BIGINT,
    datakyc_limittransaksi_penarikantunai BIGINT,
    datakyc_limittransaksi_penarikannontunai BIGINT,
    datakyc_limittransaksi_frekuensi BIGINT,
    datakyc_datanasabahperusahaan_penghasilan BIGINT,
    tglbukacif_date VARCHAR(64),
    tglbukacif_timezone_type BIGINT,
    tglbukacif_timezone VARCHAR(64),
    kolekbi_manual BIGINT,
    kolekbpr_manual BIGINT,
    kolekbi_pinjaman BIGINT,
    kolekbpr_pinjaman BIGINT,
    rec_koreksi_oleh TEXT,
    rec_koreksi_tgljam_date VARCHAR(64),
    rec_koreksi_tgljam_type TEXT,
    rec_koreksi_lokasi TEXT,
    profilresiko_identitasnasabah TEXT,
    profilresiko_lokasiusaha TEXT,
    profilresiko_jumlahtransaksi TEXT,
    profilresiko_kegiatanusaha TEXT,
    profilresiko_strukturkepemilikan TEXT,
    profilresiko_produkjasajaringan TEXT,
    profilresiko_informasilain TEXT,
    profilresiko_resumeakhir TEXT,
    profilresiko_profil TEXT,
    rec_dibuat_oleh TEXT,
    rec_dibuat_tgljam_date VARCHAR(64),
    rec_dibuat_tgljam_type TEXT,
    rec_dibuat_lokasi TEXT,
    rec_diupdate_oleh TEXT,
    rec_diupdate_tgljam_date VARCHAR(64),
    rec_diupdate_tgljam_type TEXT,
    rec_diupdate_lokasi TEXT,
    rec_timestamp_date VARCHAR(64),
    rec_timestamp_type TEXT,
    status_dokumen TEXT,
    plafondlimit TEXT,
    customfield TEXT,
    datadiklat TEXT,
    location_locationname TEXT,
    fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cif_data_pengurus_perusahaan (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cif_id VARCHAR(64) NOT NULL,
    id VARCHAR(64),
    nocif TEXT,
    nourut BIGINT,
    nama TEXT,
    nonpwp TEXT,
    tempatlahir TEXT,
    tgllahir_date VARCHAR(64),
    tgllahir_timezone_type BIGINT,
    tgllahir_timezone VARCHAR(64),
    jeniskelamin TEXT,
    noktp TEXT,
    tgldikeluarkan TEXT,
    berlakusampai TEXT,
    berlakuseumurhidup TEXT,
    jabatanpengurus TEXT,
    kepemilikansaham BIGINT,
    alamatpengurus_alamat1 TEXT,
    alamatpengurus_alamat2 TEXT,
    alamatpengurus_rt TEXT,
    alamatpengurus_rw TEXT,
    alamatpengurus_kelurahan TEXT,
    alamatpengurus_kecamatan TEXT,
    alamatpengurus_kota TEXT,
    alamatpengurus_propinsi TEXT,
    alamatpengurus_kodepos TEXT,
    alamatpengurus_kodearea TEXT,
    alamatpengurus_notelp TEXT,
    alamatpengurus_nohp TEXT,
    alamatpengurus_nofax TEXT,
    tempat_dikeluarkan TEXT,
    rec_timestamp_date VARCHAR(64),
    rec_timestamp_type TEXT,
    KEY idx_cif_data_pengurus_cif_id (cif_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cif_data_ahli_waris (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cif_id VARCHAR(64) NOT NULL,
    id VARCHAR(64),
    nourut TEXT,
    nocif TEXT,
    ahliwaris_nama TEXT,
    ahliwaris_hubdgnkontak TEXT,
    ahliwaris_alamat1 TEXT,
    ahliwaris_alamat2 TEXT,
    ahliwaris_rt TEXT,
    ahliwaris_rw TEXT,
    ahliwaris_kelurahan TEXT,
    ahliwaris_kecamatan TEXT,
    ahliwaris_kota TEXT,
    ahliwaris_propinsi TEXT,
    ahliwaris_notelp TEXT,
    ahliwaris_nohp TEXT,
    ahliwaris_nofax TEXT,
    ahliwaris_kodepos TEXT,
    rec_timestamp_date VARCHAR(64),
    rec_timestamp_type TEXT,
    KEY idx_cif_data_ahli_waris_cif_id (cif_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cif_tabungan (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cif_id VARCHAR(64) NOT NULL,
    id VARCHAR(64),
    currency TEXT,
    status_dokumen TEXT,
    noalt TEXT,
    tglbukarekening TEXT,
    nama TEXT,
    KEY idx_cif_tabungan_cif_id (cif_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS savings (
    norekening VARCHAR(64) PRIMARY KEY,
    locationid TEXT,
    rec_dibuat_lokasi TEXT,
    noalt TEXT,
    noalt2 TEXT,
    nocif TEXT,
    produkid TEXT,
    nama TEXT,
    status_dokumen TEXT,
    status_cif TEXT,
    createdate_date VARCHAR(64),
    createdate_timezone_type BIGINT,
    createdate_timezone VARCHAR(64),
    createdby TEXT,
    produk_jenistabungan TEXT,
    currency TEXT,
    sukubungakredit TEXT,
    pembayaranbunga_kredit_tgltetap BIGINT,
    sukubungadebit TEXT,
    pembayaranbunga_debit_tgltetap BIGINT,
    overdraft TEXT,
    norek_tujuan_bunga TEXT,
    namanasabah TEXT,
    jenistabungan TEXT,
    cetakbilyet TEXT,
    cetakbukutabungan TEXT,
    produk_sukubungadebit BIGINT,
    produk_sukubungakredit DOUBLE,
    referral TEXT,
    produk_transaksiautodebit TEXT,
    tujuanpembukaanrekening TEXT,
    sumberdana TEXT,
    jointaccount TEXT,
    alasanblokir TEXT,
    nilaibukablokir BIGINT,
    tglblokir TEXT,
    tglakhirblokir TEXT,
    keteranganblokir TEXT,
    tglbukablokir TEXT,
    alasanbukablokir TEXT,
    saldoblokir BIGINT,
    tglbukarekening_date VARCHAR(64),
    tglbukarekening_timezone_type BIGINT,
    tglbukarekening_timezone VARCHAR(64),
    tglclosed TEXT,
    blokirdebet TEXT,
    blokirkredit TEXT,
    namarek TEXT,
    namalain TEXT,
    jenisnasabah TEXT,
    dataalamat_ktp_alamat1 TEXT,
    tglbukacif_date VARCHAR(64),
    tglbukacif_timezone_type BIGINT,
    tglbukacif_timezone VARCHAR(64),
    dataalamat_ktp_alamat2 TEXT,
    dataalamat_ktp_rt TEXT,
    dataalamat_ktp_rw TEXT,
    dataalamat_ktp_propinsi TEXT,
    dataalamat_ktp_kota TEXT,
    dataalamat_ktp_kecamatan TEXT,
    dataalamat_ktp_kelurahan TEXT,
    dataalamat_ktp_kodepos TEXT,
    saldoawal DOUBLE,
    saldoakhir DOUBLE,
    mutasidebit TEXT,
    mutasikredit TEXT,
    saldoakru DOUBLE,
    saldoakrudebit BIGINT,
    plafondlimit BIGINT,
    dpd BIGINT,
    kolekbi BIGINT,
    tunggakan TEXT,
    denda_tunggakan TEXT,
    tgl_mulai_tunggakan TEXT,
    tgl_bayar_terakhir TEXT,
    sid_golongankredit TEXT,
    sid_jenispenggunaan TEXT,
    sid_jenisusaha TEXT,
    sid_orientasipenggunaan TEXT,
    sid_sumberdanapelunasan TEXT,
    sid_sifatkredit TEXT,
    sid_sifatkredit2 TEXT,
    sid_sektorekonomi TEXT,
    sid_sektorekonomi2 TEXT,
    terpakai BIGINT,
    plafond_blokir TEXT,
    total_so_aktif BIGINT,
    totalusedplafondod1 BIGINT,
    totalavailableplafondod1 BIGINT,
    totalavailableplafond BIGINT,
    limitfasilitas BIGINT,
    periodeawal_fasilitas TEXT,
    periodeakhir_fasilitas TEXT,
    periode_batas_fasilitas_pencairan TEXT,
    keterangan_fasilitas TEXT,
    produk_bnpl TEXT,
    mid_rate BIGINT,
    serviceid TEXT,
    groupid TEXT,
    kode_marketing TEXT,
    notes_marketing TEXT,
    totalavailableplafondod BIGINT,
    totalusedplafondod BIGINT,
    saldoawalkredit TEXT,
    saldoawaldebit TEXT,
    saldoakhirkredit TEXT,
    saldoakhirkredit_equivalent TEXT,
    saldoakhirdebit TEXT,
    saldoakhirdebit_equivalent TEXT,
    saldoakrubungakredit DOUBLE,
    saldoakrubungadebit BIGINT,
    datastandingorder TEXT,
    attKtp TINYINT(1),
    attTtd TINYINT(1),
    statusblokir TEXT,
    fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loans (
    id VARCHAR(64) PRIMARY KEY,
    locationid TEXT,
    rec_dibuat_lokasi TEXT,
    restruktur_noakad_akhir TEXT,
    restruktur_tanggalakhirakad_date VARCHAR(64),
    restruktur_tanggalakhirakad_timezone_type BIGINT,
    restruktur_tanggalakhirakad_timezone VARCHAR(64),
    restruktur_tanggalawal TEXT,
    restruktur_tanggalakhir TEXT,
    restruktur_cara TEXT,
    restruktur_frekuensi TEXT,
    tanggalmulaitunggakan TEXT,
    lokasi TEXT,
    nopk TEXT,
    namanasabah TEXT,
    aliasnama TEXT,
    statusrekening TEXT,
    tgl_pencairan TEXT,
    rec_dibuat_oleh TEXT,
    noalt TEXT,
    produk_jenispinjaman TEXT,
    produkid TEXT,
    idproduk TEXT,
    currency TEXT,
    plafondlimit TEXT,
    jmlpokok_pinjaman TEXT,
    jangkawaktu TEXT,
    produk_jenisangsuran TEXT,
    tgl_angsuran BIGINT,
    sid_sifatkredit2 TEXT,
    sid_jenispenggunaan TEXT,
    sid_sumberdanapelunasan TEXT,
    sid_golongankredit TEXT,
    sid_orientasipenggunaan TEXT,
    sid_sektorekonomi TEXT,
    pejabatkredit TEXT,
    pejabatkreditdua TEXT,
    sid_sektorekonomi2 TEXT,
    sid_sifatkredit TEXT,
    datapenjamin TEXT,
    mengetahuisuamiistri TEXT,
    dp_nama TEXT,
    dp_noktp TEXT,
    dp_alamat TEXT,
    dp_tempatlahir TEXT,
    dp_tgllahir TEXT,
    dp_jeniskelamin TEXT,
    dp_goldarah TEXT,
    dp_agama TEXT,
    dp_statusperkawinan TEXT,
    dp_pekerjaan TEXT,
    dp_nocif TEXT,
    dp_hubungan TEXT,
    dp_kewarganegaraan TEXT,
    dp_tempatterbit TEXT,
    dp_tglterbit TEXT,
    dp_berlakuseumurhidup TEXT,
    dp_tglberlakusampai TEXT,
    sid_jenisusaha TEXT,
    bungaflat DOUBLE,
    noperjanjiankredit TEXT,
    journalid TEXT,
    persendendatunggakan BIGINT,
    bungaberjenjang TEXT,
    norekgabungan_bnpl TEXT,
    tgl_tutup TEXT,
    titipan BIGINT,
    periode TEXT,
    produk_sukubunga DOUBLE,
    produk_perubahansukubunga TEXT,
    tujuankredit TEXT,
    tglterakhir_bayarpokokdanbunga_date VARCHAR(64),
    tglterakhir_bayarpokokdanbunga_timezone_type BIGINT,
    tglterakhir_bayarpokokdanbunga_timezone VARCHAR(64),
    tglbayarpokokbunga_berikutnya_date VARCHAR(64),
    tglbayarpokokbunga_berikutnya_timezone_type BIGINT,
    tglbayarpokokbunga_berikutnya_timezone VARCHAR(64),
    tgljtterakhir_date VARCHAR(64),
    tgljtterakhir_timezone_type BIGINT,
    tgljtterakhir_timezone VARCHAR(64),
    tgljtberikutnya_date VARCHAR(64),
    tgljtberikutnya_timezone_type BIGINT,
    tgljtberikutnya_timezone VARCHAR(64),
    outstandingpinjaman TEXT,
    tunggakanpokok TEXT,
    accrue TEXT,
    decimalpoint BIGINT,
    tunggakanbunga TEXT,
    denda_tunggakan TEXT,
    dpd BIGINT,
    kolekbi BIGINT,
    kolekbpr BIGINT,
    updatekolekbi TEXT,
    totalcollateralvalue BIGINT,
    totalassetvalue BIGINT,
    nocif TEXT,
    jenisnasabah TEXT,
    tglbukacif_date VARCHAR(64),
    tglbukacif_timezone_type BIGINT,
    tglbukacif_timezone VARCHAR(64),
    status_dokumen TEXT,
    dataalamat_ktp_alamat1 TEXT,
    dataalamat_ktp_alamat2 TEXT,
    dataalamat_ktp_rt TEXT,
    dataalamat_ktp_rw TEXT,
    dataalamat_ktp_kelurahan TEXT,
    dataalamat_ktp_kecamatan TEXT,
    dataalamat_ktp_kota TEXT,
    dataalamat_ktp_propinsi TEXT,
    dataalamat_ktp_kodepos TEXT,
    dataalamat_rumah_nohp TEXT,
    norektab_pencairanpinjaman TEXT,
    norektab_bayarangsuran TEXT,
    norektab_pencairanpinjaman2 TEXT,
    norektab_bayarangsuran2 TEXT,
    jenisjaminan2 TEXT,
    jenisjaminan TEXT,
    totalnilaipasar TEXT,
    terpakai BIGINT,
    totalnilaijaminan BIGINT,
    jaminan TEXT,
    jmlagunan BIGINT,
    tglhapusbuku TEXT,
    totalhapusbuku TEXT,
    nilaihapusbuku_saldopinjaman TEXT,
    nilaihapusbuku_bungaberjalan TEXT,
    nilaihapusbuku_tunggakanbunga TEXT,
    nilaihapusbuku_tunggakandenda TEXT,
    ppapblnterakhir TEXT,
    ppaptglterakhir TEXT,
    marketing TEXT,
    datacs_notes TEXT,
    analiskredit TEXT,
    analiskredit_notes TEXT,
    ht_pokok TEXT,
    ht_bunga TEXT,
    tglhapustagih TEXT,
    total_ht TEXT,
    jmlpokok_pinjaman2 BIGINT,
    totalnilaipasar2 BIGINT,
    serviceid TEXT,
    groupid TEXT,
    jenisjaminantanah TEXT,
    jenisjaminanlainnya TEXT,
    tempatpenyimpanan TINYINT(1),
    channeling TINYINT(1),
    asuransidata TEXT,
    fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loan_datatanah_bangunan (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    loan_id VARCHAR(64) NOT NULL,
    tanah_nosertifikat TEXT,
    tanah_statussertifikat TEXT,
    tanah_imb TEXT,
    tanah_noimb TEXT,
    tanah_lokasi TEXT,
    tanah_rt TEXT,
    tanah_rw TEXT,
    tanah_kelurahan TEXT,
    tanah_kecamatan TEXT,
    tanah_kota TEXT,
    tanah_provinsi TEXT,
    tanah_luas TEXT,
    tanah_surattanahdikeluarkan TEXT,
    tanah_kodepos TEXT,
    tanah_atasnama TEXT,
    tanah_nilaijaminan BIGINT,
    tanah_nilaipasar BIGINT,
    sid_jenispengikatan TEXT,
    sid_datidua TEXT,
    ansuransi TEXT,
    tglpenilaian_date VARCHAR(64),
    tglpenilaian_timezone_type BIGINT,
    tglpenilaian_timezone VARCHAR(64),
    tanah_nilaijaminanreal BIGINT,
    persenppap TEXT,
    tanah_tglsertifikat TEXT,
    tanah_nosuratukur TEXT,
    tanah_tglukur TEXT,
    KEY idx_loan_datatanah_bangunan_loan_id (loan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loan_biaya_pencairan (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    loan_id VARCHAR(64) NOT NULL,
    namabiaya TEXT,
    jumlah_biaya TEXT,
    hitungdwp TEXT,
    KEY idx_loan_biaya_pencairan_loan_id (loan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loan_tabungan (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    loan_id VARCHAR(64) NOT NULL,
    id VARCHAR(64),
    namanasabah TEXT,
    produkid TEXT,
    tglbukarekening_date VARCHAR(64),
    tglbukarekening_timezone_type BIGINT,
    tglbukarekening_timezone VARCHAR(64),
    currency TEXT,
    status_dokumen TEXT,
    saldo TEXT,
    saldodebit TEXT,
    KEY idx_loan_tabungan_loan_id (loan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loan_jadwal_angsuran (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    loan_id VARCHAR(64) NOT NULL,
    tanggal TEXT,
    angsuran TEXT,
    bunga TEXT,
    pokok TEXT,
    denda TEXT,
    bayar_pokok TEXT,
    bayar_denda TEXT,
    bayar_bunga TEXT,
    sisapinjaman TEXT,
    statusbayar TEXT,
    angsuranke BIGINT,
    KEY idx_loan_jadwal_angsuran_loan_id (loan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loan_history_bayar (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    loan_id VARCHAR(64) NOT NULL,
    tgl_date VARCHAR(64),
    tgl_timezone_type BIGINT,
    tgl_timezone VARCHAR(64),
    angsuranke BIGINT,
    tglbayar TEXT,
    currency TEXT,
    tgljt TEXT,
    totalbayar TEXT,
    bayar_pokok TEXT,
    bayar_bunga TEXT,
    bayar_denda TEXT,
    bayar_dendapelunasan TEXT,
    nominaldwp TEXT,
    nojurnal TEXT,
    cabang TEXT,
    keterangan TEXT,
    officer TEXT,
    otor TEXT,
    KEY idx_loan_history_bayar_loan_id (loan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loan_rekening_bungaberjenjang (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    loan_id VARCHAR(64) NOT NULL,
    id TEXT,
    nourut TEXT,
    norekening TEXT,
    tenor BIGINT,
    bunga DOUBLE,
    rec_timestamp_date VARCHAR(64),
    rec_timestamp_type TEXT,
    KEY idx_loan_rekening_bungaberjenjang_loan_id (loan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
